name: Build Flet APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o projeto
        uses: actions/checkout@v4

      - name: Gerar APK
        id: build
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          runner-python-version: "3.14"
          bundled-python-version: "3.14"
          build-number: ${{ github.run_number }}

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: pong-apk
          path: ${{ steps.build.outputs.archive-path }}
          if-no-files-found: error